     <link rel="stylesheet" href="{{ asset('public/assets/admin/css/pos_calendar.css') }}">

     <div class="modal fade" id="calendarModal" tabindex="-1" aria-labelledby="calendarModalLabel" aria-hidden="true">
         <div class="modal-dialog modal-lg">
             <div class="modal-content">
                 <div class="modal-header">
                     <h5 class="modal-title" id="exampleModalLabel">Calendar</h5>
                     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                     </button>
                 </div>
                 <div class="modal-body">
                     <div class="header">
                         <div class="controls">
                             <button class="btn btn-select active" onclick="setView('calendar')">Calendar View</button>
                             <button class="btn btn-select" onclick="setView('year')">Year View</button>
                             @if (request()->routeIs('admin.pos.dashboard'))
                                 <a href="{{ route('admin.pos.calendar-export') }}?month={{ date('m') }}&year={{ date('Y') }}"
                                     class="export_calendar_btn btn btn-outline-primary">Export <span
                                         class="text_span"></span></a>
                             @endif 
                             <div class="navigation">
                                 <button class="nav-btn" onclick="navigate(-1)">‹</button>
                                 <div class="current-period" id="currentPeriod">August 2024</div>
                                 <button class="nav-btn" onclick="navigate(1)">›</button>
                             </div>
                             @if (request()->routeIs('admin.pos.dashboard'))
                                 <form action="" style="min-width: 144px;" class="d-flex">
                                     <select class="form-control mx-1 js-select2-custom" id="branch_id" name="branch_cl"
                                         onchange="this.form.submit()">
                                         <option value="all">All</option>
                                         @foreach ($data['branches'] as $key => $branch)
                                             <option {{ request()->branch_cl == $branch->id ? 'selected' : '' }}
                                                 value="{{ $branch->id }}">{{ ucfirst($branch->name) }}</option>
                                         @endforeach
                                     </select>
                                 </form>
                             @endif
                         </div>
                     </div>

                     <div class="calendar-container">
                         <div id="calendarView" class="calendar">
                             <!-- Calendar will be generated by JavaScript -->
                         </div>

                         <div id="yearView" class="year-view">
                             <!-- Year view will be generated by JavaScript -->
                         </div>
                     </div>
                     @if(!request()->routeIs('admin.account.*'))
                     <div class="d-flex gap-1 p-3">
                         <div class="d-flex align-items-center">
                             <span class="calendar-day low legend"></span>
                             <span class="legend-text">Low Sales</span>
                         </div>
                         <div class="d-flex align-items-center">
                             <span class="calendar-day medium legend"></span>
                             <span class="legend-text"> Medium Sales</span>
                         </div>
                         <div class="d-flex align-items-center">
                             <span class="calendar-day high legend"></span>
                             <span class="legend-text"> High Sales</span>
                         </div>
                     </div>
                        @endif
                 </div>
                 <div class="modal-footer">
                     <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                 </div>
             </div>
         </div>
     </div>
