name: Deploy to All Server

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: admin
            host: 64.227.158.127
            path: /var/www/html/admin

          - name: vendor
            host: 167.71.233.92
            path: /var/www/html/vendor

          - name: shop
            host: 64.227.178.210
            path: /var/www/html/mychitti

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ matrix.host }} >> ~/.ssh/known_hosts

    - name: Deploy Code to ${{ matrix.name }} Server
      run: |
        ssh root@${{ matrix.host }} << 'EOF'
          set -e
          cd ${{ matrix.path }}

          echo "Fetching latest code..."
          git fetch origin
          git reset --hard origin/main


          echo "Installing dependencies..."
          composer install --no-dev --optimize-autoloader --no-interaction

          echo "Clearing caches..."
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear

          echo "Rebuilding caches..."
          php artisan config:cache
          php artisan view:cache

          echo "Fixing Laravel permissions (excluding DO Spaces mount)..."
          chown -R apache:apache storage/framework storage/logs bootstrap/cache
          chmod -R 775 storage/framework storage/logs bootstrap/cache

          echo "Running migrations..."
          php artisan migrate --force

          echo "Deployment completed successfully!"
        EOF
